name: Python application test with GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest jupytext pandas numpy seaborn matplotlib statsmodels
        pip install ipython pytest 
        
    - name: Convert Notebooks
      run: jupytext --to py example_time_series.ipynb
    - name: Execute PyTest on library 
      run: pytest test-ts_lib-functions.py
    - name: Execute PyTest for data consistency
      run: pytest test-consistency_ts.py
    